# coding: utf-8

# flake8: noqa
from __future__ import absolute_import
# import models into model package
from swagger_server.models.huishouden import Huishouden
from swagger_server.models.huishouden_bri import HuishoudenBri
from swagger_server.models.huishouden_bri_inkomens import HuishoudenBriInkomens
from swagger_server.models.huishouden_bri_inkomens2019 import HuishoudenBriInkomens2019
from swagger_server.models.huishouden_brp import HuishoudenBrp
from swagger_server.models.huishouden_inkomens import HuishoudenInkomens
from swagger_server.models.huishouden_verklaring import HuishoudenVerklaring
from swagger_server.models.persoon import Persoon
from swagger_server.models.toets_resultaat_lokale_binding import ToetsResultaatLokaleBinding
from swagger_server.models.toets_resultaat_met_kale_huur import ToetsResultaatMetKaleHuur
from swagger_server.models.toets_resultaat_segmenten import ToetsResultaatSegmenten
from swagger_server.models.woonduren import Woonduren
from swagger_server.models.woonduren_inner import WoondurenInner
