# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.huishouden_bri_inkomens import HuishoudenBriInkomens  # noqa: F401,E501
from swagger_server import util


class HuishoudenBri(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, inkomens: HuishoudenBriInkomens=None):  # noqa: E501
        """HuishoudenBri - a model defined in Swagger

        :param inkomens: The inkomens of this HuishoudenBri.  # noqa: E501
        :type inkomens: HuishoudenBriInkomens
        """
        self.swagger_types = {
            'inkomens': HuishoudenBriInkomens
        }

        self.attribute_map = {
            'inkomens': 'inkomens'
        }
        self._inkomens = inkomens

    @classmethod
    def from_dict(cls, dikt) -> 'HuishoudenBri':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The huishouden_bri of this HuishoudenBri.  # noqa: E501
        :rtype: HuishoudenBri
        """
        return util.deserialize_model(dikt, cls)

    @property
    def inkomens(self) -> HuishoudenBriInkomens:
        """Gets the inkomens of this HuishoudenBri.


        :return: The inkomens of this HuishoudenBri.
        :rtype: HuishoudenBriInkomens
        """
        return self._inkomens

    @inkomens.setter
    def inkomens(self, inkomens: HuishoudenBriInkomens):
        """Sets the inkomens of this HuishoudenBri.


        :param inkomens: The inkomens of this HuishoudenBri.
        :type inkomens: HuishoudenBriInkomens
        """

        self._inkomens = inkomens
