# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.huishouden_inkomens import HuishoudenInkomens  # noqa: F401,E501
from swagger_server import util


class Huishouden(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, inkomens: List[HuishoudenInkomens]=None, aantal_meeverhuizende_kinderen: int=None, kale_huur: int=None):  # noqa: E501
        """Huishouden - a model defined in Swagger

        :param inkomens: The inkomens of this Huishouden.  # noqa: E501
        :type inkomens: List[HuishoudenInkomens]
        :param aantal_meeverhuizende_kinderen: The aantal_meeverhuizende_kinderen of this Huishouden.  # noqa: E501
        :type aantal_meeverhuizende_kinderen: int
        :param kale_huur: The kale_huur of this Huishouden.  # noqa: E501
        :type kale_huur: int
        """
        self.swagger_types = {
            'inkomens': List[HuishoudenInkomens],
            'aantal_meeverhuizende_kinderen': int,
            'kale_huur': int
        }

        self.attribute_map = {
            'inkomens': 'inkomens',
            'aantal_meeverhuizende_kinderen': 'aantalMeeverhuizendeKinderen',
            'kale_huur': 'kaleHuur'
        }
        self._inkomens = inkomens
        self._aantal_meeverhuizende_kinderen = aantal_meeverhuizende_kinderen
        self._kale_huur = kale_huur

    @classmethod
    def from_dict(cls, dikt) -> 'Huishouden':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The huishouden of this Huishouden.  # noqa: E501
        :rtype: Huishouden
        """
        return util.deserialize_model(dikt, cls)

    @property
    def inkomens(self) -> List[HuishoudenInkomens]:
        """Gets the inkomens of this Huishouden.


        :return: The inkomens of this Huishouden.
        :rtype: List[HuishoudenInkomens]
        """
        return self._inkomens

    @inkomens.setter
    def inkomens(self, inkomens: List[HuishoudenInkomens]):
        """Sets the inkomens of this Huishouden.


        :param inkomens: The inkomens of this Huishouden.
        :type inkomens: List[HuishoudenInkomens]
        """

        self._inkomens = inkomens

    @property
    def aantal_meeverhuizende_kinderen(self) -> int:
        """Gets the aantal_meeverhuizende_kinderen of this Huishouden.


        :return: The aantal_meeverhuizende_kinderen of this Huishouden.
        :rtype: int
        """
        return self._aantal_meeverhuizende_kinderen

    @aantal_meeverhuizende_kinderen.setter
    def aantal_meeverhuizende_kinderen(self, aantal_meeverhuizende_kinderen: int):
        """Sets the aantal_meeverhuizende_kinderen of this Huishouden.


        :param aantal_meeverhuizende_kinderen: The aantal_meeverhuizende_kinderen of this Huishouden.
        :type aantal_meeverhuizende_kinderen: int
        """

        self._aantal_meeverhuizende_kinderen = aantal_meeverhuizende_kinderen

    @property
    def kale_huur(self) -> int:
        """Gets the kale_huur of this Huishouden.


        :return: The kale_huur of this Huishouden.
        :rtype: int
        """
        return self._kale_huur

    @kale_huur.setter
    def kale_huur(self, kale_huur: int):
        """Sets the kale_huur of this Huishouden.


        :param kale_huur: The kale_huur of this Huishouden.
        :type kale_huur: int
        """

        self._kale_huur = kale_huur
