openapi: 3.0.1
info:
  title: verhuurtoetsen
  description: API voor AEDES verhuurtoetsen hackaton
  version: "0.5"
servers:
- url: http://localhost:8080/
security:
- AuthorizationHeader: []
paths:
  /aedes/verhuurtoets/passendheidstoets-bri-met-kale-huur/:
    post:
      tags:
      - AEDES verhuurtoetsen
      summary: Toetst kale huur volgens het geldende nationale toetsingskader
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- huishouden zie def onder  -------
              $ref: '#/components/schemas/huishouden'
      responses:
        200:
          description: Succesvol toetsresultaat
          content:
            application/json:
              schema:
                #  ----- toetsResultaat zie def onder  -------
                $ref: '#/components/schemas/toets-resultaat-met-kale-huur'
        400:
          description: Request Failed.
          content: {}
  /aedes/verhuurtoets/passendheidstoets-bri-segmenten/:
    post:
      tags:
      - AEDES verhuurtoetsen
      summary: Toetst verhuursegmenten van huurder(s) volgens het geldende nationale toetsingskader
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- huishouden zie def onder  -------
              $ref: '#/components/schemas/huishouden'
      responses:
        200:
          description: Succesvol toetsresultaat
          content:
            application/json:
              schema:
                #  ----- toetsResultaat zie def onder  -------
                $ref: '#/components/schemas/toets-resultaat-segmenten'
        400:
          description: Request Failed.
          content: {}
  /aedes/verhuurtoets/lokale-bindings-toets/:
    post:
      tags:
      - AEDES verhuurtoetsen
      summary: Toetst woonduur volgens lokaal geldende toetsingskader
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- huishouden zie def onder  -------
              $ref: '#/components/schemas/woonduren'
      responses:
        200:
          description: Succesvol toetsresultaat
          content:
            application/json:
              schema:
                #  ----- toetsResultaat zie def onder  -------
                $ref: '#/components/schemas/toets-resultaat-lokale-binding'
        400:
          description: Request Failed.
          content: {}
components:
  securitySchemes:
    AuthorizationHeader:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    huishouden:
      type: object
      properties: 
        inkomens: 
          type: array
          items:
            $ref: '#/components/schemas/inkomen'
        inkomensOndertekend: 
          type: array
          items:
            type: string
        controleerHandtekening:
          type: boolean
          default: "false"
        aantalMeeverhuizendeKinderen: 
          type: integer
          format: int32
        kaleHuur: 
          type: integer
          format: int32
          
    inkomen:
          type: object
          properties: 
              jti: 
                type: string
              iat: 
                type: integer
                format: int32
              nbf: 
                type: integer
                format: int32
              exp: 
                type: integer
                format: int32
              iss: 
                type: string
              aud: 
                type: string
              sub: 
                type: string
              brp: 
                type: object
                properties: 
                  voornamen: 
                    type: string
                  voorvoegselGeslachtsnaam: 
                    type: string
                  geslachtsnaam: 
                    type: string
                  voorvoegselPartnernaam: 
                    type: string
                    format: nullable
                  partnernaam: 
                    type: string
                    format: nullable
                  huisnummer: 
                    type: string
                  huisletter: 
                    type: string
                  huisnummerToevoeging: 
                    type: string
                  huisnummerAanduiding: 
                    type: string
                  postcode: 
                    type: string
                  geboortedatum: 
                    type: string
              bri: 
                type: object
                properties: 
                  inkomens: 
                    type: object
                    properties: 
                      2019: 
                        type: object
                        properties: 
                          inkomen: 
                            type: integer
                            format: int32
                          grondslag: 
                            type: string
                          status: 
                            type: string
                      2020: 
                        type: object
                        properties: 
                          inkomen: 
                            type: integer
                            format: int32
                          grondslag: 
                            type: string
                          status: 
                            type: string
              verklaring: 
                type: object
                properties: 
                  tekst: 
                    type: string
                  authenticatiedienst: 
                    type: string
                  betrouwbaarheidsniveau: 
                    type: string
                  tijdstempelAuthenticatie: 
                    type: integer
                    format: int32
                    
    woonduren:
          type: array
          items: 
            type: object
            properties: 
              voornamen: 
                type: string
              voorvoegselGeslachtsnaam: 
                type: string
              geslachtsnaam: 
                type: string
              woonduur:
                type: integer
                format: int32

    persoon:
          type: object
          properties: 
            voornamen: 
              type: string
            voorvoegselGeslachtsnaam: 
              type: string
            geslachtsnaam: 
              type: string
          
    toets-resultaat-met-kale-huur: 
      type: object
      properties: 
        personen:
          type: array
          items:
            $ref: '#/components/schemas/persoon'
        toets-resultaat: 
          type: boolean
        tijdstempel:
          type: string
        jwt: 
          type: string

    toets-resultaat-segmenten: 
      type: object
      properties: 
        personen:
          type: array
          items:
            $ref: '#/components/schemas/persoon'
        toets-resultaat-tot-hoge-aftoppingsgrens: 
          type: boolean
        toets-resultaat-tot-lage-aftoppingsgrens: 
          type: boolean
        tijdstempel:
          type: string
        jwt: 
          type: string

    toets-resultaat-lokale-binding: 
      type: object
      properties:
        personen:
          type: array
          items:
            $ref: '#/components/schemas/persoon'
        toets-resultaat-lokale-binding: 
          type: boolean
        tijdstempel:
          type: string
        jwt: 
          type: string
        