swagger: "2.0"
info:
  description: API for Deactivating Customer Accounts
  version: "0.1"
  title: Deactivate Customer Account
host: localhost:8080
basePath: "/"
schemes:
- http
consumes:
- application/json
produces:
- application/json
security:
  - Authorization-Header: []
paths:
  /customer/deactivate/{cust_id}:
    put:
      tags:
      - "Deactivate Customer"
      summary: "Deactivate Customer Account"
      operationId: deactivate
      parameters:
      - name: cust_id
        in: path
        required: true
        type: string
      responses:
        200:
          description: "Customer Deactivated"
        400:
          description: Request Failed.
securityDefinitions:
  Authorization-Header:
    type: apiKey
    name: Authorization
    in: header