# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HuishoudenInkomensOndertekend(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, inkomen_ondertekend: str=None):  # noqa: E501
        """HuishoudenInkomensOndertekend - a model defined in Swagger

        :param inkomen_ondertekend: The inkomen_ondertekend of this HuishoudenInkomensOndertekend.  # noqa: E501
        :type inkomen_ondertekend: str
        """
        self.swagger_types = {
            'inkomen_ondertekend': str
        }

        self.attribute_map = {
            'inkomen_ondertekend': 'inkomenOndertekend'
        }
        self._inkomen_ondertekend = inkomen_ondertekend

    @classmethod
    def from_dict(cls, dikt) -> 'HuishoudenInkomensOndertekend':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The huishouden_inkomensOndertekend of this HuishoudenInkomensOndertekend.  # noqa: E501
        :rtype: HuishoudenInkomensOndertekend
        """
        return util.deserialize_model(dikt, cls)

    @property
    def inkomen_ondertekend(self) -> str:
        """Gets the inkomen_ondertekend of this HuishoudenInkomensOndertekend.


        :return: The inkomen_ondertekend of this HuishoudenInkomensOndertekend.
        :rtype: str
        """
        return self._inkomen_ondertekend

    @inkomen_ondertekend.setter
    def inkomen_ondertekend(self, inkomen_ondertekend: str):
        """Sets the inkomen_ondertekend of this HuishoudenInkomensOndertekend.


        :param inkomen_ondertekend: The inkomen_ondertekend of this HuishoudenInkomensOndertekend.
        :type inkomen_ondertekend: str
        """

        self._inkomen_ondertekend = inkomen_ondertekend
