# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inkomen_bri_inkomens import InkomenBriInkomens  # noqa: F401,E501
from swagger_server import util


class InkomenBri(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, inkomens: InkomenBriInkomens=None):  # noqa: E501
        """InkomenBri - a model defined in Swagger

        :param inkomens: The inkomens of this InkomenBri.  # noqa: E501
        :type inkomens: InkomenBriInkomens
        """
        self.swagger_types = {
            'inkomens': InkomenBriInkomens
        }

        self.attribute_map = {
            'inkomens': 'inkomens'
        }
        self._inkomens = inkomens

    @classmethod
    def from_dict(cls, dikt) -> 'InkomenBri':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inkomen_bri of this InkomenBri.  # noqa: E501
        :rtype: InkomenBri
        """
        return util.deserialize_model(dikt, cls)

    @property
    def inkomens(self) -> InkomenBriInkomens:
        """Gets the inkomens of this InkomenBri.


        :return: The inkomens of this InkomenBri.
        :rtype: InkomenBriInkomens
        """
        return self._inkomens

    @inkomens.setter
    def inkomens(self, inkomens: InkomenBriInkomens):
        """Sets the inkomens of this InkomenBri.


        :param inkomens: The inkomens of this InkomenBri.
        :type inkomens: InkomenBriInkomens
        """

        self._inkomens = inkomens
