# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Persoon(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, voornamen: str=None, voorvoegsel_geslachtsnaam: str=None, geslachtsnaam: str=None):  # noqa: E501
        """Persoon - a model defined in Swagger

        :param voornamen: The voornamen of this Persoon.  # noqa: E501
        :type voornamen: str
        :param voorvoegsel_geslachtsnaam: The voorvoegsel_geslachtsnaam of this Persoon.  # noqa: E501
        :type voorvoegsel_geslachtsnaam: str
        :param geslachtsnaam: The geslachtsnaam of this Persoon.  # noqa: E501
        :type geslachtsnaam: str
        """
        self.swagger_types = {
            'voornamen': str,
            'voorvoegsel_geslachtsnaam': str,
            'geslachtsnaam': str
        }

        self.attribute_map = {
            'voornamen': 'voornamen',
            'voorvoegsel_geslachtsnaam': 'voorvoegselGeslachtsnaam',
            'geslachtsnaam': 'geslachtsnaam'
        }
        self._voornamen = voornamen
        self._voorvoegsel_geslachtsnaam = voorvoegsel_geslachtsnaam
        self._geslachtsnaam = geslachtsnaam

    @classmethod
    def from_dict(cls, dikt) -> 'Persoon':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The persoon of this Persoon.  # noqa: E501
        :rtype: Persoon
        """
        return util.deserialize_model(dikt, cls)

    @property
    def voornamen(self) -> str:
        """Gets the voornamen of this Persoon.


        :return: The voornamen of this Persoon.
        :rtype: str
        """
        return self._voornamen

    @voornamen.setter
    def voornamen(self, voornamen: str):
        """Sets the voornamen of this Persoon.


        :param voornamen: The voornamen of this Persoon.
        :type voornamen: str
        """

        self._voornamen = voornamen

    @property
    def voorvoegsel_geslachtsnaam(self) -> str:
        """Gets the voorvoegsel_geslachtsnaam of this Persoon.


        :return: The voorvoegsel_geslachtsnaam of this Persoon.
        :rtype: str
        """
        return self._voorvoegsel_geslachtsnaam

    @voorvoegsel_geslachtsnaam.setter
    def voorvoegsel_geslachtsnaam(self, voorvoegsel_geslachtsnaam: str):
        """Sets the voorvoegsel_geslachtsnaam of this Persoon.


        :param voorvoegsel_geslachtsnaam: The voorvoegsel_geslachtsnaam of this Persoon.
        :type voorvoegsel_geslachtsnaam: str
        """

        self._voorvoegsel_geslachtsnaam = voorvoegsel_geslachtsnaam

    @property
    def geslachtsnaam(self) -> str:
        """Gets the geslachtsnaam of this Persoon.


        :return: The geslachtsnaam of this Persoon.
        :rtype: str
        """
        return self._geslachtsnaam

    @geslachtsnaam.setter
    def geslachtsnaam(self, geslachtsnaam: str):
        """Sets the geslachtsnaam of this Persoon.


        :param geslachtsnaam: The geslachtsnaam of this Persoon.
        :type geslachtsnaam: str
        """

        self._geslachtsnaam = geslachtsnaam
