# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.persoon import Persoon  # noqa: F401,E501
from swagger_server import util


class ToetsResultaatSegmenten(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, personen: List[Persoon]=None, toets_resultaat_tot_hoge_aftoppingsgrens: bool=None, toets_resultaat_tot_lage_aftoppingsgrens: bool=None, jwt: str=None):  # noqa: E501
        """ToetsResultaatSegmenten - a model defined in Swagger

        :param personen: The personen of this ToetsResultaatSegmenten.  # noqa: E501
        :type personen: List[Persoon]
        :param toets_resultaat_tot_hoge_aftoppingsgrens: The toets_resultaat_tot_hoge_aftoppingsgrens of this ToetsResultaatSegmenten.  # noqa: E501
        :type toets_resultaat_tot_hoge_aftoppingsgrens: bool
        :param toets_resultaat_tot_lage_aftoppingsgrens: The toets_resultaat_tot_lage_aftoppingsgrens of this ToetsResultaatSegmenten.  # noqa: E501
        :type toets_resultaat_tot_lage_aftoppingsgrens: bool
        :param jwt: The jwt of this ToetsResultaatSegmenten.  # noqa: E501
        :type jwt: str
        """
        self.swagger_types = {
            'personen': List[Persoon],
            'toets_resultaat_tot_hoge_aftoppingsgrens': bool,
            'toets_resultaat_tot_lage_aftoppingsgrens': bool,
            'jwt': str
        }

        self.attribute_map = {
            'personen': 'personen',
            'toets_resultaat_tot_hoge_aftoppingsgrens': 'toets-resultaat-tot-hoge-aftoppingsgrens',
            'toets_resultaat_tot_lage_aftoppingsgrens': 'toets-resultaat-tot-lage-aftoppingsgrens',
            'jwt': 'jwt'
        }
        self._personen = personen
        self._toets_resultaat_tot_hoge_aftoppingsgrens = toets_resultaat_tot_hoge_aftoppingsgrens
        self._toets_resultaat_tot_lage_aftoppingsgrens = toets_resultaat_tot_lage_aftoppingsgrens
        self._jwt = jwt

    @classmethod
    def from_dict(cls, dikt) -> 'ToetsResultaatSegmenten':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The toets-resultaat-segmenten of this ToetsResultaatSegmenten.  # noqa: E501
        :rtype: ToetsResultaatSegmenten
        """
        return util.deserialize_model(dikt, cls)

    @property
    def personen(self) -> List[Persoon]:
        """Gets the personen of this ToetsResultaatSegmenten.


        :return: The personen of this ToetsResultaatSegmenten.
        :rtype: List[Persoon]
        """
        return self._personen

    @personen.setter
    def personen(self, personen: List[Persoon]):
        """Sets the personen of this ToetsResultaatSegmenten.


        :param personen: The personen of this ToetsResultaatSegmenten.
        :type personen: List[Persoon]
        """

        self._personen = personen

    @property
    def toets_resultaat_tot_hoge_aftoppingsgrens(self) -> bool:
        """Gets the toets_resultaat_tot_hoge_aftoppingsgrens of this ToetsResultaatSegmenten.


        :return: The toets_resultaat_tot_hoge_aftoppingsgrens of this ToetsResultaatSegmenten.
        :rtype: bool
        """
        return self._toets_resultaat_tot_hoge_aftoppingsgrens

    @toets_resultaat_tot_hoge_aftoppingsgrens.setter
    def toets_resultaat_tot_hoge_aftoppingsgrens(self, toets_resultaat_tot_hoge_aftoppingsgrens: bool):
        """Sets the toets_resultaat_tot_hoge_aftoppingsgrens of this ToetsResultaatSegmenten.


        :param toets_resultaat_tot_hoge_aftoppingsgrens: The toets_resultaat_tot_hoge_aftoppingsgrens of this ToetsResultaatSegmenten.
        :type toets_resultaat_tot_hoge_aftoppingsgrens: bool
        """

        self._toets_resultaat_tot_hoge_aftoppingsgrens = toets_resultaat_tot_hoge_aftoppingsgrens

    @property
    def toets_resultaat_tot_lage_aftoppingsgrens(self) -> bool:
        """Gets the toets_resultaat_tot_lage_aftoppingsgrens of this ToetsResultaatSegmenten.


        :return: The toets_resultaat_tot_lage_aftoppingsgrens of this ToetsResultaatSegmenten.
        :rtype: bool
        """
        return self._toets_resultaat_tot_lage_aftoppingsgrens

    @toets_resultaat_tot_lage_aftoppingsgrens.setter
    def toets_resultaat_tot_lage_aftoppingsgrens(self, toets_resultaat_tot_lage_aftoppingsgrens: bool):
        """Sets the toets_resultaat_tot_lage_aftoppingsgrens of this ToetsResultaatSegmenten.


        :param toets_resultaat_tot_lage_aftoppingsgrens: The toets_resultaat_tot_lage_aftoppingsgrens of this ToetsResultaatSegmenten.
        :type toets_resultaat_tot_lage_aftoppingsgrens: bool
        """

        self._toets_resultaat_tot_lage_aftoppingsgrens = toets_resultaat_tot_lage_aftoppingsgrens

    @property
    def jwt(self) -> str:
        """Gets the jwt of this ToetsResultaatSegmenten.


        :return: The jwt of this ToetsResultaatSegmenten.
        :rtype: str
        """
        return self._jwt

    @jwt.setter
    def jwt(self, jwt: str):
        """Sets the jwt of this ToetsResultaatSegmenten.


        :param jwt: The jwt of this ToetsResultaatSegmenten.
        :type jwt: str
        """

        self._jwt = jwt
