# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HuishoudenVerklaring(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tekst: str=None, authenticatiedienst: str=None, betrouwbaarheidsniveau: str=None, tijdstempel_authenticatie: int=None):  # noqa: E501
        """HuishoudenVerklaring - a model defined in Swagger

        :param tekst: The tekst of this HuishoudenVerklaring.  # noqa: E501
        :type tekst: str
        :param authenticatiedienst: The authenticatiedienst of this HuishoudenVerklaring.  # noqa: E501
        :type authenticatiedienst: str
        :param betrouwbaarheidsniveau: The betrouwbaarheidsniveau of this HuishoudenVerklaring.  # noqa: E501
        :type betrouwbaarheidsniveau: str
        :param tijdstempel_authenticatie: The tijdstempel_authenticatie of this HuishoudenVerklaring.  # noqa: E501
        :type tijdstempel_authenticatie: int
        """
        self.swagger_types = {
            'tekst': str,
            'authenticatiedienst': str,
            'betrouwbaarheidsniveau': str,
            'tijdstempel_authenticatie': int
        }

        self.attribute_map = {
            'tekst': 'tekst',
            'authenticatiedienst': 'authenticatiedienst',
            'betrouwbaarheidsniveau': 'betrouwbaarheidsniveau',
            'tijdstempel_authenticatie': 'tijdstempelAuthenticatie'
        }
        self._tekst = tekst
        self._authenticatiedienst = authenticatiedienst
        self._betrouwbaarheidsniveau = betrouwbaarheidsniveau
        self._tijdstempel_authenticatie = tijdstempel_authenticatie

    @classmethod
    def from_dict(cls, dikt) -> 'HuishoudenVerklaring':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Huishouden_verklaring of this HuishoudenVerklaring.  # noqa: E501
        :rtype: HuishoudenVerklaring
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tekst(self) -> str:
        """Gets the tekst of this HuishoudenVerklaring.


        :return: The tekst of this HuishoudenVerklaring.
        :rtype: str
        """
        return self._tekst

    @tekst.setter
    def tekst(self, tekst: str):
        """Sets the tekst of this HuishoudenVerklaring.


        :param tekst: The tekst of this HuishoudenVerklaring.
        :type tekst: str
        """

        self._tekst = tekst

    @property
    def authenticatiedienst(self) -> str:
        """Gets the authenticatiedienst of this HuishoudenVerklaring.


        :return: The authenticatiedienst of this HuishoudenVerklaring.
        :rtype: str
        """
        return self._authenticatiedienst

    @authenticatiedienst.setter
    def authenticatiedienst(self, authenticatiedienst: str):
        """Sets the authenticatiedienst of this HuishoudenVerklaring.


        :param authenticatiedienst: The authenticatiedienst of this HuishoudenVerklaring.
        :type authenticatiedienst: str
        """

        self._authenticatiedienst = authenticatiedienst

    @property
    def betrouwbaarheidsniveau(self) -> str:
        """Gets the betrouwbaarheidsniveau of this HuishoudenVerklaring.


        :return: The betrouwbaarheidsniveau of this HuishoudenVerklaring.
        :rtype: str
        """
        return self._betrouwbaarheidsniveau

    @betrouwbaarheidsniveau.setter
    def betrouwbaarheidsniveau(self, betrouwbaarheidsniveau: str):
        """Sets the betrouwbaarheidsniveau of this HuishoudenVerklaring.


        :param betrouwbaarheidsniveau: The betrouwbaarheidsniveau of this HuishoudenVerklaring.
        :type betrouwbaarheidsniveau: str
        """

        self._betrouwbaarheidsniveau = betrouwbaarheidsniveau

    @property
    def tijdstempel_authenticatie(self) -> int:
        """Gets the tijdstempel_authenticatie of this HuishoudenVerklaring.


        :return: The tijdstempel_authenticatie of this HuishoudenVerklaring.
        :rtype: int
        """
        return self._tijdstempel_authenticatie

    @tijdstempel_authenticatie.setter
    def tijdstempel_authenticatie(self, tijdstempel_authenticatie: int):
        """Sets the tijdstempel_authenticatie of this HuishoudenVerklaring.


        :param tijdstempel_authenticatie: The tijdstempel_authenticatie of this HuishoudenVerklaring.
        :type tijdstempel_authenticatie: int
        """

        self._tijdstempel_authenticatie = tijdstempel_authenticatie
