version: '3'

networks:
  default:

services:
    aedes:
      container_name: inkomenstoets
      image: local/aedestoetsapi:0.4  
      restart: always
      networks:
        - default
      environment:
        VIRTUAL_HOST: 'aedes.dikw.nl'
        LETSENCRYPT_HOST: aedes.dikw.nl
        LETSENCRYPT_EMAIL: hugo.koopmans@dikw.com
        LETSENCRYPT_TEST: 'true'
        ACME_CA_URI: 'https://acme-staging.api.letsencrypt.org/directory'


