# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ToetsResultaat(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, passend: bool=None, passend_tot_hoge_aftoppingsgrens: bool=None, passend_tot_lage_aftoppingsgrens: bool=None):  # noqa: E501
        """ToetsResultaat - a model defined in Swagger

        :param passend: The passend of this ToetsResultaat.  # noqa: E501
        :type passend: bool
        :param passend_tot_hoge_aftoppingsgrens: The passend_tot_hoge_aftoppingsgrens of this ToetsResultaat.  # noqa: E501
        :type passend_tot_hoge_aftoppingsgrens: bool
        :param passend_tot_lage_aftoppingsgrens: The passend_tot_lage_aftoppingsgrens of this ToetsResultaat.  # noqa: E501
        :type passend_tot_lage_aftoppingsgrens: bool
        """
        self.swagger_types = {
            'passend': bool,
            'passend_tot_hoge_aftoppingsgrens': bool,
            'passend_tot_lage_aftoppingsgrens': bool
        }

        self.attribute_map = {
            'passend': 'passend',
            'passend_tot_hoge_aftoppingsgrens': 'passendTotHogeAftoppingsgrens',
            'passend_tot_lage_aftoppingsgrens': 'passendTotLageAftoppingsgrens'
        }
        self._passend = passend
        self._passend_tot_hoge_aftoppingsgrens = passend_tot_hoge_aftoppingsgrens
        self._passend_tot_lage_aftoppingsgrens = passend_tot_lage_aftoppingsgrens

    @classmethod
    def from_dict(cls, dikt) -> 'ToetsResultaat':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The toetsResultaat of this ToetsResultaat.  # noqa: E501
        :rtype: ToetsResultaat
        """
        return util.deserialize_model(dikt, cls)

    @property
    def passend(self) -> bool:
        """Gets the passend of this ToetsResultaat.


        :return: The passend of this ToetsResultaat.
        :rtype: bool
        """
        return self._passend

    @passend.setter
    def passend(self, passend: bool):
        """Sets the passend of this ToetsResultaat.


        :param passend: The passend of this ToetsResultaat.
        :type passend: bool
        """

        self._passend = passend

    @property
    def passend_tot_hoge_aftoppingsgrens(self) -> bool:
        """Gets the passend_tot_hoge_aftoppingsgrens of this ToetsResultaat.


        :return: The passend_tot_hoge_aftoppingsgrens of this ToetsResultaat.
        :rtype: bool
        """
        return self._passend_tot_hoge_aftoppingsgrens

    @passend_tot_hoge_aftoppingsgrens.setter
    def passend_tot_hoge_aftoppingsgrens(self, passend_tot_hoge_aftoppingsgrens: bool):
        """Sets the passend_tot_hoge_aftoppingsgrens of this ToetsResultaat.


        :param passend_tot_hoge_aftoppingsgrens: The passend_tot_hoge_aftoppingsgrens of this ToetsResultaat.
        :type passend_tot_hoge_aftoppingsgrens: bool
        """

        self._passend_tot_hoge_aftoppingsgrens = passend_tot_hoge_aftoppingsgrens

    @property
    def passend_tot_lage_aftoppingsgrens(self) -> bool:
        """Gets the passend_tot_lage_aftoppingsgrens of this ToetsResultaat.


        :return: The passend_tot_lage_aftoppingsgrens of this ToetsResultaat.
        :rtype: bool
        """
        return self._passend_tot_lage_aftoppingsgrens

    @passend_tot_lage_aftoppingsgrens.setter
    def passend_tot_lage_aftoppingsgrens(self, passend_tot_lage_aftoppingsgrens: bool):
        """Sets the passend_tot_lage_aftoppingsgrens of this ToetsResultaat.


        :param passend_tot_lage_aftoppingsgrens: The passend_tot_lage_aftoppingsgrens of this ToetsResultaat.
        :type passend_tot_lage_aftoppingsgrens: bool
        """

        self._passend_tot_lage_aftoppingsgrens = passend_tot_lage_aftoppingsgrens
