openapi: 3.0.1
info:
  title: Inkomenstoets
  description: API voor AEDES inkomenstoets hackaton
  version: "0.1"
servers:
- url: http://localhost:8080/
security:
- AuthorizationHeader: []
paths:
  /huurder/nationale_inkomenstoets/:
    post:
      tags:
      - Toets inkomen nationale toets eisen
      summary: Toetst inkomen van huurder volgens de geldende nationale toetsingskader
      operationId: huurder_nationale_inkomenstoets_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Huishouden'
        required: true
      responses:
        "200":
          description: Succesvol toetsresultaat
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/toetsResultaat'
        "400":
          description: Request Failed.
          content: {}
      x-openapi-router-controller: swagger_server.controllers.toets_inkomen_nationale_toets_eisen_controller
components:
  schemas:
    Huishouden:
      type: object
      properties:
        inkomens:
          type: array
          items:
            $ref: '#/components/schemas/Huishouden_inkomens'
        aantalMeeverhuizendeKinderen:
          type: integer
          format: int32
        kaleHuur:
          type: integer
          format: int32
    toetsResultaat:
      type: object
      properties:
        passend:
          type: boolean
        passendTotHogeAftoppingsgrens:
          type: boolean
        passendTotLageAftoppingsgrens:
          type: boolean
      example:
        passend: true
        passendTotHogeAftoppingsgrens: true
        passendTotLageAftoppingsgrens: true
    Huishouden_brp:
      type: object
      properties:
        voornamen:
          type: string
        voorvoegselGeslachtsnaam:
          type: string
        geslachtsnaam:
          type: string
        voorvoegselPartnernaam:
          type: string
          format: nullable
        partnernaam:
          type: string
          format: nullable
        huisnummer:
          type: string
        huisletter:
          type: string
        huisnummerToevoeging:
          type: string
        huisnummerAanduiding:
          type: string
        postcode:
          type: string
        geboortedatum:
          type: string
    Huishouden_bri_inkomens_2019:
      type: object
      properties:
        inkomen:
          type: integer
          format: int32
        grondslag:
          type: string
        status:
          type: string
    Huishouden_bri_inkomens:
      type: object
      properties:
        "2019":
          $ref: '#/components/schemas/Huishouden_bri_inkomens_2019'
        "2020":
          $ref: '#/components/schemas/Huishouden_bri_inkomens_2019'
    Huishouden_bri:
      type: object
      properties:
        inkomens:
          $ref: '#/components/schemas/Huishouden_bri_inkomens'
    Huishouden_verklaring:
      type: object
      properties:
        tekst:
          type: string
        authenticatiedienst:
          type: string
        betrouwbaarheidsniveau:
          type: string
        tijdstempelAuthenticatie:
          type: integer
          format: int32
    Huishouden_inkomens:
      type: object
      properties:
        jti:
          type: string
        iat:
          type: integer
          format: int32
        nbf:
          type: integer
          format: int32
        exp:
          type: integer
          format: int32
        iss:
          type: string
        aud:
          type: string
        sub:
          type: string
        brp:
          $ref: '#/components/schemas/Huishouden_brp'
        bri:
          $ref: '#/components/schemas/Huishouden_bri'
        verklaring:
          $ref: '#/components/schemas/Huishouden_verklaring'
  securitySchemes:
    AuthorizationHeader:
      type: apiKey
      name: Authorization
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_AuthorizationHeader

