# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inkomen_bri_inkomens2019 import InkomenBriInkomens2019  # noqa: F401,E501
from swagger_server import util


class InkomenBriInkomens(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _2019: InkomenBriInkomens2019=None, _2020: InkomenBriInkomens2019=None):  # noqa: E501
        """InkomenBriInkomens - a model defined in Swagger

        :param _2019: The _2019 of this InkomenBriInkomens.  # noqa: E501
        :type _2019: InkomenBriInkomens2019
        :param _2020: The _2020 of this InkomenBriInkomens.  # noqa: E501
        :type _2020: InkomenBriInkomens2019
        """
        self.swagger_types = {
            '_2019': InkomenBriInkomens2019,
            '_2020': InkomenBriInkomens2019
        }

        self.attribute_map = {
            '_2019': '2019',
            '_2020': '2020'
        }
        self.__2019 = _2019
        self.__2020 = _2020

    @classmethod
    def from_dict(cls, dikt) -> 'InkomenBriInkomens':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inkomen_bri_inkomens of this InkomenBriInkomens.  # noqa: E501
        :rtype: InkomenBriInkomens
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _2019(self) -> InkomenBriInkomens2019:
        """Gets the _2019 of this InkomenBriInkomens.


        :return: The _2019 of this InkomenBriInkomens.
        :rtype: InkomenBriInkomens2019
        """
        return self.__2019

    @_2019.setter
    def _2019(self, _2019: InkomenBriInkomens2019):
        """Sets the _2019 of this InkomenBriInkomens.


        :param _2019: The _2019 of this InkomenBriInkomens.
        :type _2019: InkomenBriInkomens2019
        """

        self.__2019 = _2019

    @property
    def _2020(self) -> InkomenBriInkomens2019:
        """Gets the _2020 of this InkomenBriInkomens.


        :return: The _2020 of this InkomenBriInkomens.
        :rtype: InkomenBriInkomens2019
        """
        return self.__2020

    @_2020.setter
    def _2020(self, _2020: InkomenBriInkomens2019):
        """Sets the _2020 of this InkomenBriInkomens.


        :param _2020: The _2020 of this InkomenBriInkomens.
        :type _2020: InkomenBriInkomens2019
        """

        self.__2020 = _2020
