# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.persoon import Persoon  # noqa: F401,E501
from swagger_server import util


class ToetsResultaatLokaleBinding(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, personen: List[Persoon]=None, toets_resultaat_lokale_binding: bool=None, tijdstempel: str=None, jwt: str=None):  # noqa: E501
        """ToetsResultaatLokaleBinding - a model defined in Swagger

        :param personen: The personen of this ToetsResultaatLokaleBinding.  # noqa: E501
        :type personen: List[Persoon]
        :param toets_resultaat_lokale_binding: The toets_resultaat_lokale_binding of this ToetsResultaatLokaleBinding.  # noqa: E501
        :type toets_resultaat_lokale_binding: bool
        :param tijdstempel: The tijdstempel of this ToetsResultaatLokaleBinding.  # noqa: E501
        :type tijdstempel: str
        :param jwt: The jwt of this ToetsResultaatLokaleBinding.  # noqa: E501
        :type jwt: str
        """
        self.swagger_types = {
            'personen': List[Persoon],
            'toets_resultaat_lokale_binding': bool,
            'tijdstempel': str,
            'jwt': str
        }

        self.attribute_map = {
            'personen': 'personen',
            'toets_resultaat_lokale_binding': 'toets-resultaat-lokale-binding',
            'tijdstempel': 'tijdstempel',
            'jwt': 'jwt'
        }
        self._personen = personen
        self._toets_resultaat_lokale_binding = toets_resultaat_lokale_binding
        self._tijdstempel = tijdstempel
        self._jwt = jwt

    @classmethod
    def from_dict(cls, dikt) -> 'ToetsResultaatLokaleBinding':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The toets-resultaat-lokale-binding of this ToetsResultaatLokaleBinding.  # noqa: E501
        :rtype: ToetsResultaatLokaleBinding
        """
        return util.deserialize_model(dikt, cls)

    @property
    def personen(self) -> List[Persoon]:
        """Gets the personen of this ToetsResultaatLokaleBinding.


        :return: The personen of this ToetsResultaatLokaleBinding.
        :rtype: List[Persoon]
        """
        return self._personen

    @personen.setter
    def personen(self, personen: List[Persoon]):
        """Sets the personen of this ToetsResultaatLokaleBinding.


        :param personen: The personen of this ToetsResultaatLokaleBinding.
        :type personen: List[Persoon]
        """

        self._personen = personen

    @property
    def toets_resultaat_lokale_binding(self) -> bool:
        """Gets the toets_resultaat_lokale_binding of this ToetsResultaatLokaleBinding.


        :return: The toets_resultaat_lokale_binding of this ToetsResultaatLokaleBinding.
        :rtype: bool
        """
        return self._toets_resultaat_lokale_binding

    @toets_resultaat_lokale_binding.setter
    def toets_resultaat_lokale_binding(self, toets_resultaat_lokale_binding: bool):
        """Sets the toets_resultaat_lokale_binding of this ToetsResultaatLokaleBinding.


        :param toets_resultaat_lokale_binding: The toets_resultaat_lokale_binding of this ToetsResultaatLokaleBinding.
        :type toets_resultaat_lokale_binding: bool
        """

        self._toets_resultaat_lokale_binding = toets_resultaat_lokale_binding

    @property
    def tijdstempel(self) -> str:
        """Gets the tijdstempel of this ToetsResultaatLokaleBinding.


        :return: The tijdstempel of this ToetsResultaatLokaleBinding.
        :rtype: str
        """
        return self._tijdstempel

    @tijdstempel.setter
    def tijdstempel(self, tijdstempel: str):
        """Sets the tijdstempel of this ToetsResultaatLokaleBinding.


        :param tijdstempel: The tijdstempel of this ToetsResultaatLokaleBinding.
        :type tijdstempel: str
        """

        self._tijdstempel = tijdstempel

    @property
    def jwt(self) -> str:
        """Gets the jwt of this ToetsResultaatLokaleBinding.


        :return: The jwt of this ToetsResultaatLokaleBinding.
        :rtype: str
        """
        return self._jwt

    @jwt.setter
    def jwt(self, jwt: str):
        """Sets the jwt of this ToetsResultaatLokaleBinding.


        :param jwt: The jwt of this ToetsResultaatLokaleBinding.
        :type jwt: str
        """

        self._jwt = jwt
