# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WoondurenInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, voornamen: str=None, voorvoegsel_geslachtsnaam: str=None, geslachtsnaam: str=None, woonduur: int=None):  # noqa: E501
        """WoondurenInner - a model defined in Swagger

        :param voornamen: The voornamen of this WoondurenInner.  # noqa: E501
        :type voornamen: str
        :param voorvoegsel_geslachtsnaam: The voorvoegsel_geslachtsnaam of this WoondurenInner.  # noqa: E501
        :type voorvoegsel_geslachtsnaam: str
        :param geslachtsnaam: The geslachtsnaam of this WoondurenInner.  # noqa: E501
        :type geslachtsnaam: str
        :param woonduur: The woonduur of this WoondurenInner.  # noqa: E501
        :type woonduur: int
        """
        self.swagger_types = {
            'voornamen': str,
            'voorvoegsel_geslachtsnaam': str,
            'geslachtsnaam': str,
            'woonduur': int
        }

        self.attribute_map = {
            'voornamen': 'voornamen',
            'voorvoegsel_geslachtsnaam': 'voorvoegselGeslachtsnaam',
            'geslachtsnaam': 'geslachtsnaam',
            'woonduur': 'woonduur'
        }
        self._voornamen = voornamen
        self._voorvoegsel_geslachtsnaam = voorvoegsel_geslachtsnaam
        self._geslachtsnaam = geslachtsnaam
        self._woonduur = woonduur

    @classmethod
    def from_dict(cls, dikt) -> 'WoondurenInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The woonduren_inner of this WoondurenInner.  # noqa: E501
        :rtype: WoondurenInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def voornamen(self) -> str:
        """Gets the voornamen of this WoondurenInner.


        :return: The voornamen of this WoondurenInner.
        :rtype: str
        """
        return self._voornamen

    @voornamen.setter
    def voornamen(self, voornamen: str):
        """Sets the voornamen of this WoondurenInner.


        :param voornamen: The voornamen of this WoondurenInner.
        :type voornamen: str
        """

        self._voornamen = voornamen

    @property
    def voorvoegsel_geslachtsnaam(self) -> str:
        """Gets the voorvoegsel_geslachtsnaam of this WoondurenInner.


        :return: The voorvoegsel_geslachtsnaam of this WoondurenInner.
        :rtype: str
        """
        return self._voorvoegsel_geslachtsnaam

    @voorvoegsel_geslachtsnaam.setter
    def voorvoegsel_geslachtsnaam(self, voorvoegsel_geslachtsnaam: str):
        """Sets the voorvoegsel_geslachtsnaam of this WoondurenInner.


        :param voorvoegsel_geslachtsnaam: The voorvoegsel_geslachtsnaam of this WoondurenInner.
        :type voorvoegsel_geslachtsnaam: str
        """

        self._voorvoegsel_geslachtsnaam = voorvoegsel_geslachtsnaam

    @property
    def geslachtsnaam(self) -> str:
        """Gets the geslachtsnaam of this WoondurenInner.


        :return: The geslachtsnaam of this WoondurenInner.
        :rtype: str
        """
        return self._geslachtsnaam

    @geslachtsnaam.setter
    def geslachtsnaam(self, geslachtsnaam: str):
        """Sets the geslachtsnaam of this WoondurenInner.


        :param geslachtsnaam: The geslachtsnaam of this WoondurenInner.
        :type geslachtsnaam: str
        """

        self._geslachtsnaam = geslachtsnaam

    @property
    def woonduur(self) -> int:
        """Gets the woonduur of this WoondurenInner.


        :return: The woonduur of this WoondurenInner.
        :rtype: int
        """
        return self._woonduur

    @woonduur.setter
    def woonduur(self, woonduur: int):
        """Sets the woonduur of this WoondurenInner.


        :param woonduur: The woonduur of this WoondurenInner.
        :type woonduur: int
        """

        self._woonduur = woonduur
